plugins {
    id "com.diffplug.spotless" version "6.25.0"
}

// 버전 관리용 변수 선언
ext {
    springCloudVersion = "2023.0.0"
    springdocVersion   = "2.3.0"
}

subprojects {
    apply plugin: "com.diffplug.spotless"

    spotless {
        java {
            googleJavaFormat("1.17.0")
            indentWithTabs(2)
            endWithNewline()
            removeUnusedImports()
            trimTrailingWhitespace()
            target("src/**/*.java")
        }
        format("misc") {
            target("**/*.gradle", "**/*.md", "**/.gitignore")
            indentWithSpaces()
            trimTrailingWhitespace()
            endWithNewline()
        }
    }

    repositories {
        mavenCentral()
    }
}
