rootProject.name = "HubEleven"

include(
        "common",
        "company",
        "config",
        "delivery",
        "eurekaServer",
        "gateWay",
        "hub",
        "notification",
        "order",
        "product",
        "user"
)

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}