spring:
  config:
    import: "configserver:"
  application:
    name: delivery-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

